import jax
import jax.numpy as jnp
import flax.linen as nn
import scripts_materials.neohooke as neohooke
import scripts_materials.orthotropic as orthotropic
import scripts_materials.bonet as bonet
from scripts_surrogates.data_utils import matrix_to_tensor


def _max_eigenvalue_2x2_spd(W):
    """Compute λ_max of a 2x2 symmetric positive definite matrix (closed-form)."""
    a, b, c = W[0, 0], W[0, 1], W[1, 1]
    return 0.5 * (a + c + jnp.sqrt((a - c) ** 2 + 4 * b ** 2))


def _construct_cholesky_weight_matrix(params, w_max):
    L = jnp.array([[jax.nn.softplus(params[0]), 0.0],
                   [params[1], jax.nn.softplus(params[2])]])
    # W = L @ L.T (symmetric positive definite), scaled to bound λ_max
    W = L @ L.T
    scale = jnp.minimum(1.0, w_max / _max_eigenvalue_2x2_spd(W))
    return W * scale


class DeformationGradientLayer(nn.Module):
    """Custom layer that transforms a [b, 2, 2] input tensor into a [b*m, 2, 2] output tensor.

    This layer multiplies the input (E^Macro) with weight matrices and adds it to an Identity
    to produce multiple deformation gradient tensors per input sample (material points).

    The weight matrices are forced to be symmetric positive definite and scaled to create a deformation gradient with positive determinant.
    """
    n_matpts: int   # m: Number of material points
    w_max: float = 1.25

    @nn.compact
    def __call__(self, x, micro_params):
        # x shape: [b, 2, 2]

        # Create Cholesky parameters with shape [m, 3] for 2x2 case
        # Each 2x2 lower triangular matrix needs 3 parameters: [l11, l21, l22]
        cholesky_params = self.param('cholesky_params',
                                     # nn.initializers.normal(stddev=0.1),
                                     nn.initializers.glorot_normal(),
                                     # nn.initializers.uniform(dtype=jnp.float32),  # NOTE: uniform distribution
                                     (self.n_matpts, 3))

        # Construct weight matrices from Cholesky parameters
        weights = jax.vmap(_construct_cholesky_weight_matrix, in_axes=(0, None))(cholesky_params, self.w_max)

        # Perform the batched matrix multiplication
        E_micro = jnp.einsum('bik,mkj->bmij', x, weights)

        # Convert E to C
        C_micro = 2 * E_micro + jnp.eye(2)

        return C_micro

class HyperDeformationGradientLayer_grad(nn.Module):
    """Hypernetwork version of DeformationGradientLayer.

    The Cholesky parameters are generated by a small neural network based on micro_params,
    allowing the deformation gradient transformation to be conditioned on material properties.
    """
    n_matpts: int   # m: Number of material points
    micro_vals_used: list = None  # Subset of micro parameters to use
    w_max: float = 1.25

    @nn.compact
    def __call__(self, x, micro_params):
        hidden = nn.Dense(features=self.n_matpts, name="hyperDefGrad_hid1", use_bias=True)(micro_params[:, self.micro_vals_used])
        hidden = nn.sigmoid(hidden)
        hidden = nn.Dense(features=self.n_matpts * 2, name="hyperDefGrad_hid2", use_bias=True)(hidden)
        hidden = nn.sigmoid(hidden)
        cholesky_params = nn.Dense(features=self.n_matpts * 3, name="hyperDefGrad_out", use_bias=True)(hidden)  # [b, 3*m]
        cholesky_params = cholesky_params.reshape(-1, self.n_matpts, 3)

        weights = jax.vmap(jax.vmap(_construct_cholesky_weight_matrix, in_axes=(0, None)), in_axes=(0, None))(cholesky_params, self.w_max)

        E_micro = jnp.einsum('bij,bmjk->bmik', x, weights)
        return 2 * E_micro + jnp.eye(2)

class HyperDeformationGradientLayer(nn.Module):
    """Hypernetwork version of DeformationGradientLayer.

    The Cholesky parameters are generated by a small neural network based on micro_params,
    allowing the deformation gradient transformation to be conditioned on material properties.
    """
    n_matpts: int   # m: Number of material points
    micro_vals_used: list = None  # Subset of micro parameters to use
    w_max: float = 1.25

    @nn.compact
    def __call__(self, x, micro_params):
        # x shape: [b, 2, 2]
        # micro_params shape: [b, k] with k the number of micro parameters

        # Hypernetwork to generate Cholesky parameters
        # Each material point needs 3 Cholesky parameters: [l11, l21, l22]
        # 3L
        # Generate weight matrix W from micro_params with hidden layers
        hidden = nn.Dense(features=self.n_matpts * 6, name="hyperDefGrad_hid1", use_bias=True)(micro_params[:, self.micro_vals_used])
        hidden = nn.sigmoid(hidden)
        hidden = nn.Dense(features=self.n_matpts * 6, name="hyperDefGrad_hid2", use_bias=True)(hidden)
        hidden = nn.sigmoid(hidden)
        cholesky_params = nn.Dense(features=3 * self.n_matpts, name="hyperDefGrad_out", use_bias=True)(hidden)  # [b, 3*m]

        # Reshape to [b, m, 3]
        cholesky_params = cholesky_params.reshape(-1, self.n_matpts, 3)

        # Apply to all batch elements and material points
        # cholesky_params: [b, m, 3] -> weights: [b, m, 2, 2]
        weights = jax.vmap(jax.vmap(_construct_cholesky_weight_matrix, in_axes=(0, None)), in_axes=(0, None))(cholesky_params, self.w_max)

        # Perform the batched matrix multiplication
        # x: [b, 2, 2], weights: [b, m, 2, 2] -> result: [b, m, 2, 2]
        E_micro = jnp.einsum('bij,bmjk->bmik', x, weights)

        # Convert E to C
        C_micro = 2 * E_micro + jnp.eye(2)

        return C_micro


class HyperDeformationGradientLayer_1L(nn.Module):
    """Hypernetwork version of DeformationGradientLayer.

    The Cholesky parameters are generated by a small neural network based on micro_params,
    allowing the deformation gradient transformation to be conditioned on material properties.
    """
    n_matpts: int
    micro_vals_used: list = None
    w_max: float = 1.25

    @nn.compact
    def __call__(self, x, micro_params):
        cholesky_params = nn.Dense(features=self.n_matpts * 3, name="hyperDefGrad", use_bias=True)(micro_params[:, self.micro_vals_used])
        cholesky_params = cholesky_params.reshape(-1, self.n_matpts, 3)

        weights = jax.vmap(jax.vmap(_construct_cholesky_weight_matrix, in_axes=(0, None)), in_axes=(0, None))(cholesky_params, self.w_max)
        E_micro = jnp.einsum('bij,bmjk->bmik', x, weights)
        C_micro = 2 * E_micro + jnp.eye(2)
        return C_micro


class ResidualHyperEncoderLayer(nn.Module):
    """Residual hypernetwork for DeformationGradientLayer.

    Adds a learned linear correction to frozen base Cholesky parameters:
    cholesky = base + W @ (micro_params - micro_params_base), no bias.
    Zero deviation at the base point by construction.

    Extract base params from a trained standard PRNN:
        base_cholesky = trained_params['params']['encoder']['cholesky_params']
    """
    n_matpts: int
    base_cholesky_params: object  # [m, 3] frozen from pre-trained DeformationGradientLayer
    micro_params_base: object     # [k] micro_params of the base configuration
    max_delta: float = 1.0        # maximum absolute correction per Cholesky parameter
    micro_vals_used: list = None
    w_max: float = 1.25

    @nn.compact
    def __call__(self, x, micro_params):
        # x shape: [b, 2, 2]
        centered_micro_params = micro_params[:, self.micro_vals_used] - self.micro_params_base[jnp.array(self.micro_vals_used)]

        # # Linear version (single Dense, no bias)
        delta = nn.Dense(features=self.n_matpts * 3, use_bias=False, name="residual_encoder", kernel_init=nn.initializers.normal(stddev=1e-3))(centered_micro_params)  # [b, m*3]

        # # Nonlinear version: hidden layer + small output init for near-zero start
        # n_out = self.n_matpts * 3
        # hidden = nn.Dense(features=n_out, name="residual_enc_h1")(centered_micro_params)
        # hidden = nn.softplus(hidden)
        # delta = nn.Dense(features=n_out, name="residual_enc_out", kernel_init=nn.initializers.normal(stddev=1e-3))(hidden)  # [b, m*3]

        delta = delta.reshape(-1, self.n_matpts, 3)  # [b, m, 3]
        # delta = self.max_delta * jnp.tanh(delta)
        cholesky_params = self.base_cholesky_params[None, :, :] + delta  # [b, m, 3]

        weights = jax.vmap(jax.vmap(_construct_cholesky_weight_matrix, in_axes=(0, None)), in_axes=(0, None))(cholesky_params, self.w_max)  # [b, m, 2, 2]
        E_micro = jnp.einsum('bij,bmjk->bmik', x, weights)
        C_micro = 2 * E_micro + jnp.eye(2)
        return C_micro


class LULayer(nn.Module):
    """Custom layer that transforms a [b, 2, 2] input tensor into a [b*m, 2, 2] output tensor.

    This layer uses LU decomposition: C_micro = L @ U
    where L is a lower triangular matrix and U is an upper triangular matrix.
    A neural network generates 6 parameters per material point from the input.
    Assumes input is symmetric 2x2 matrix, so only 3 unique values are extracted.
    - For L: l11, l21, l22 (with diagonal terms exponentiated for positivity)
    - For U: u11, u12, u22 (with diagonal terms exponentiated for positivity)
    """
    n_matpts: int   # m: Number of material points

    @nn.compact
    def __call__(self, x, micro_params):
        # x shape: [b, 2, 2] - assumed symmetric
        batch_size = x.shape[0]

        # Extract unique components from symmetric matrix (upper triangular)
        # For symmetric 2x2: [[x11, x12], [x12, x22]]
        x_flat = jnp.stack([x[:, 0, 0], x[:, 1, 1], x[:, 0, 1]], axis=1)  # [b, 3]

        # Neural network to generate parameters for each material point
        # Output: [b, m, 6] where 6 = [l11, l21, l22, u11, u12, u22]
        params = nn.Dense(features=self.n_matpts * 6, name="lu_NN", use_bias=False)(x_flat)
        params = params.reshape(batch_size, self.n_matpts, 6)  # [b, m, 6]

        def construct_C_micro(param_vector):
            """Construct C_micro = L @ U from 6 parameters"""
            l11, l21, l22, u11, u12, u22 = param_vector

            # L - lower triangular matrix (diagonal terms exponentiated for positivity)
            L = jnp.array([[jnp.exp(l11), 0.0],
                          [l21, jnp.exp(l22)]])

            # U - upper triangular matrix (diagonal terms exponentiated for positivity)
            U = jnp.array([[jnp.exp(u11), u12],
                          [0.0, jnp.exp(u22)]])

            # C_micro = L @ U
            return L @ U

        # Apply to all batch elements and material points
        # params: [b, m, 6] -> C_micro: [b, m, 2, 2]
        C_micro = jax.vmap(jax.vmap(construct_C_micro))(params)

        return C_micro


class HyperLULayer(nn.Module):
    n_matpts: int
    micro_vals_used: list = None

    @nn.compact
    def __call__(self, x, micro_params):
        x_flat = jnp.stack([x[:, 0, 0], x[:, 1, 1], x[:, 0, 1]], axis=1)  # [b, 3]

        # Generate weight matrix W from micro_params
        W_flat = nn.Dense(features= 3 * self.n_matpts * 6, name="lu_weight_gen", use_bias=False)(micro_params[:, self.micro_vals_used]) # [b, 3*m*6]
        W = W_flat.reshape(-1, 3, self.n_matpts * 6)  # [b, 3, m*6]

        # Multiply x_flat [b, 3] with W [b, 3, m*6] to get params [b, m*6]
        params_flat = jnp.einsum('bi,bij->bj', x_flat, W)  # [b, m*6]
        lu_params = params_flat.reshape(-1, self.n_matpts, 6)  # [b, m, 6]

        def construct_C_micro(param_vector):
            """Construct C_micro = L @ U from 6 parameters"""
            l11, l21, l22, u11, u12, u22 = param_vector
            L = jnp.array([[jnp.exp(l11), 0.0],
                          [l21, jnp.exp(l22)]])
            U = jnp.array([[jnp.exp(u11), u12],
                          [0.0, jnp.exp(u22)]])
            return L @ U

        # Apply to all batch elements and material points
        C_micro = jax.vmap(jax.vmap(construct_C_micro))(lu_params)  # [b, m, 6] -> C_micro: [b, m, 2, 2]

        return C_micro


class HyperLUSoftLayer(nn.Module):
    """
    HyperLULayer using softplus instead of exp for diagonal elements.
    Uses softplus(x) - ln(2) + 1, which gives identity (1.0) at x=0 while being less nonlinear than exp.
    """
    n_matpts: int
    micro_vals_used: list = None

    @nn.compact
    def __call__(self, x, micro_params):
        x_flat = jnp.stack([x[:, 0, 0], x[:, 1, 1], x[:, 0, 1]], axis=1)  # [b, 3]

        # 3L
        # Generate weight matrix W from micro_params with hidden layers
        hidden = nn.Dense(features=self.n_matpts * 6, name="lu_hidden", use_bias=True)(micro_params[:, self.micro_vals_used])
        # hidden = nn.relu(hidden)
        hidden = nn.sigmoid(hidden)
        hidden = nn.Dense(features=self.n_matpts * 6, name="lu_hidden2", use_bias=True)(hidden)
        # hidden = nn.relu(hidden)
        hidden = nn.sigmoid(hidden)
        W_flat = nn.Dense(features=3 * self.n_matpts * 6, name="lu_weight_gen", use_bias=True)(hidden)  # [b, 3*m*6]
        W = W_flat.reshape(-1, 3, self.n_matpts * 6)  # [b, 3, m*6]

        # # 2L
        # # Generate weight matrix W from micro_params with hidden layer
        # hidden = nn.Dense(features=self.n_matpts * 6, name="lu_hidden", use_bias=True)(micro_params[:, self.micro_vals_used])
        # # hidden = nn.relu(hidden)
        # hidden = nn.sigmoid(hidden)
        # #  W_flat = nn.Dense(features=3 * self.n_matpts * 6, name="lu_weight_gen", use_bias=False)(hidden)  # [b, 3*m*6]
        # W_flat = nn.Dense(features=3 * self.n_matpts * 6, name="lu_weight_gen", use_bias=True)(hidden)  # [b, 3*m*6]
        # W = W_flat.reshape(-1, 3, self.n_matpts * 6)  # [b, 3, m*6]

        # # 1L
        # # Generate weight matrix W from micro_params
        # # W_flat = nn.Dense(features= 3 * self.n_matpts * 6, name="lu_weight_gen", use_bias=False)(micro_params[:, self.micro_vals_used]) # [b, 3*m*6]
        # W_flat = nn.Dense(features= 3 * self.n_matpts * 6, name="lu_weight_gen", use_bias=True)(micro_params[:, self.micro_vals_used]) # [b, 3*m*6]
        # W = W_flat.reshape(-1, 3, self.n_matpts * 6)  # [b, 3, m*6]

        # Multiply x_flat [b, 3] with W [b, 3, m*6] to get params [b, m*6]
        params_flat = jnp.einsum('bi,bij->bj', x_flat, W)  # [b, m*6]
        lu_params = params_flat.reshape(-1, self.n_matpts, 6)  # [b, m, 6]

        def construct_C_micro(param_vector):
            """Construct C_micro = L @ U from 6 parameters"""
            l11, l21, l22, u11, u12, u22 = param_vector
            # Modified softplus: softplus(x) - softplus(0) + 1, ensuring x= all 0 gives identity output
            softplus_offset = jnp.log(2.0)
            L = jnp.array([[nn.softplus(l11) - softplus_offset + 1.0, 0.0],
                          [l21, nn.softplus(l22) - softplus_offset + 1.0]])
            U = jnp.array([[nn.softplus(u11) - softplus_offset + 1.0, u12],
                          [0.0, nn.softplus(u22) - softplus_offset + 1.0]])
            return L @ U
        C_micro = jax.vmap(jax.vmap(construct_C_micro))(lu_params)  # [b, m, 6] -> C_micro: [b, m, 2, 2]
        return C_micro


class HyperLUSoftSimplerLayer(nn.Module):
    """
    4 instead of 6 params to generate L U
    """
    n_matpts: int
    micro_vals_used: list = None

    @nn.compact
    def __call__(self, x, micro_params):
        x_flat = jnp.stack([x[:, 0, 0], x[:, 1, 1], x[:, 0, 1]], axis=1)  # [b, 3]

        # 3L
        # Generate weight matrix W from micro_params with hidden layers
        hidden = nn.Dense(features=self.n_matpts * 4, name="lu_hidden", use_bias=True)(micro_params[:, self.micro_vals_used])
        # hidden = nn.relu(hidden)
        hidden = nn.sigmoid(hidden)
        hidden = nn.Dense(features=self.n_matpts * 4, name="lu_hidden2", use_bias=True)(hidden)
        # hidden = nn.relu(hidden)
        hidden = nn.sigmoid(hidden)
        W_flat = nn.Dense(features=3 * self.n_matpts * 4, name="lu_weight_gen", use_bias=True)(hidden)  # [b, 3*m*6]
        W = W_flat.reshape(-1, 3, self.n_matpts * 4)  # [b, 3, m*6]

        # Multiply x_flat [b, 3] with W [b, 3, m*6] to get params [b, m*6]
        params_flat = jnp.einsum('bi,bij->bj', x_flat, W)  # [b, m*6]
        lu_params = params_flat.reshape(-1, self.n_matpts, 4)  # [b, m, 6]

        def construct_C_micro(param_vector):
            """Construct C_micro = L @ U from 4 parameters"""
            l21, u11, u12, u22 = param_vector
            # Modified softplus: softplus(x) - softplus(0) + 1, ensuring x= all 0 gives identity output
            softplus_offset = jnp.log(2.0)
            L = jnp.array([[1.0, 0.0],
                          [l21, 1.0]])
            U = jnp.array([[nn.softplus(u11) - softplus_offset + 1.0, u12],
                          [0.0, nn.softplus(u22) - softplus_offset + 1.0]])
            return L @ U
        C_micro = jax.vmap(jax.vmap(construct_C_micro))(lu_params)  # [b, m, 6] -> C_micro: [b, m, 2, 2]
        return C_micro


class LUv2Layer(nn.Module):
    """Standard (non-hyper) LUv2 encoder layer.

    A 1-hidden-layer MLP maps strain to LU parameters per material point.
    Uses bias shift (MLP(x) - MLP(0)) to ensure zero strain -> identity.
    Same inner MLP architecture as HyperLUv2Layer, but with fixed learned weights.
    """
    n_matpts: int
    hidden_dim: int = 8

    @nn.compact
    def __call__(self, x, micro_params):
        x_flat = jnp.stack([x[:, 0, 0], x[:, 1, 1], x[:, 0, 1]], axis=1)  # [b, 3]

        dense1 = nn.Dense(features=self.hidden_dim, name="lu_dense1")
        dense_out = nn.Dense(features=self.n_matpts * 4, name="lu_dense_out")

        def mlp(inp):
            h = nn.softplus(dense1(inp))
            return dense_out(h)

        # Bias shift: MLP(x) - MLP(0) to ensure 0 in = 0 out
        params_flat = mlp(x_flat) - mlp(jnp.zeros_like(x_flat))  # [b, n_matpts*4]
        lu_params = params_flat.reshape(-1, self.n_matpts, 4)  # [b, m, 4]

        def construct_C_micro(param_vector):
            """Construct C_micro = L @ U from 4 parameters.
            L is lower unit triangular (1s on diagonal), U has elu+1 on diagonal.
            """
            l21, u11, u12, u22 = param_vector
            L = jnp.array([[1.0, 0.0],
                          [l21, 1.0]])
            U = jnp.array([[nn.elu(u11) + 1.0, u12],
                          [0.0, nn.elu(u22) + 1.0]])
            return L @ U

        C_micro = jax.vmap(jax.vmap(construct_C_micro))(lu_params)
        return C_micro


class ResidualHyperLUv2EncoderLayer(nn.Module):
    """Residual hypernetwork for LUv2Layer.

    Adds learned linear corrections to the frozen base MLP parameters (W1, b1, W2, b2):
    W1 = base_W1 + dW1(micro_params - micro_params_base), etc.
    Zero deviation at the base point by construction.

    Extract base params from a trained LUv2Layer:
        base_mlp_params = {
            'lu_dense1': trained_params['params']['encoder']['lu_dense1'],
            'lu_dense_out': trained_params['params']['encoder']['lu_dense_out'],
        }
    """
    n_matpts: int
    base_mlp_params: object    # dict with frozen base MLP weights from LUv2Layer
    micro_params_base: object  # [k] micro_params of the base configuration
    hidden_dim: int = 8
    micro_vals_used: list = None

    @nn.compact
    def __call__(self, x, micro_params):
        x_flat = jnp.stack([x[:, 0, 0], x[:, 1, 1], x[:, 0, 1]], axis=1)  # [b, 3]

        # Frozen base MLP params
        base_W1 = self.base_mlp_params['lu_dense1']['kernel']      # [3, hidden_dim]
        base_b1 = self.base_mlp_params['lu_dense1']['bias']        # [hidden_dim]
        base_W2 = self.base_mlp_params['lu_dense_out']['kernel']   # [hidden_dim, n_matpts*4]
        base_b2 = self.base_mlp_params['lu_dense_out']['bias']     # [n_matpts*4]

        total_mlp_params = base_W1.size + base_b1.size + base_W2.size + base_b2.size

        # Generate corrections to all MLP params from centered micro_params
        centered = micro_params[:, self.micro_vals_used] - self.micro_params_base[jnp.array(self.micro_vals_used)]
        delta_flat = nn.Dense(features=total_mlp_params, use_bias=False, name="residual_encoder", kernel_init=nn.initializers.normal(stddev=1e-3))(centered)  # [b, total_mlp_params]

        # Unpack deltas and add to frozen base params
        idx = 0
        W1 = base_W1[None] + delta_flat[:, idx:idx + base_W1.size].reshape(-1, *base_W1.shape)
        idx += base_W1.size
        b1 = base_b1[None] + delta_flat[:, idx:idx + base_b1.size].reshape(-1, *base_b1.shape)
        idx += base_b1.size
        W2 = base_W2[None] + delta_flat[:, idx:idx + base_W2.size].reshape(-1, *base_W2.shape)
        idx += base_W2.size
        b2 = base_b2[None] + delta_flat[:, idx:idx + base_b2.size].reshape(-1, *base_b2.shape)

        # Forward pass through corrected MLP (batched, since W1..b2 are now per-sample)
        def mlp_forward(inp):
            h = nn.softplus(jnp.einsum('bi,bij->bj', inp, W1) + b1)
            return jnp.einsum('bi,bij->bj', h, W2) + b2

        # Bias shift: MLP(x) - MLP(0) to ensure 0 in = 0 out
        params_flat = mlp_forward(x_flat) - mlp_forward(jnp.zeros_like(x_flat))
        lu_params = params_flat.reshape(-1, self.n_matpts, 4)  # [b, m, 4]

        def construct_C_micro(param_vector):
            l21, u11, u12, u22 = param_vector
            L = jnp.array([[1.0, 0.0],
                          [l21, 1.0]])
            U = jnp.array([[nn.elu(u11) + 1.0, u12],
                          [0.0, nn.elu(u22) + 1.0]])
            return L @ U

        C_micro = jax.vmap(jax.vmap(construct_C_micro))(lu_params)
        return C_micro

class HyperLUv2Layer(nn.Module):
    """
    Version 2:
    - reduced nonlinearity in the LU itself, by using lower unit triangle
    - Increased generality to allow bias & arbitrary activations while ensuring 0 in = 0 out, by using a bias shift (out = MLP(x) - MLP(0))
    """
    n_matpts: int
    hidden_dim: int = 8
    micro_vals_used: list = None

    @nn.compact
    def __call__(self, x, micro_params):
        x_flat = jnp.stack([x[:, 0, 0], x[:, 1, 1], x[:, 0, 1]], axis=1)  # [b, 3]

        # Hypernetwork generates weights and biases for the 2-layer network
        # Layer 1: W1 [3, hidden_dim], b1 [hidden_dim]
        # Layer 2: W2 [hidden_dim, n_matpts*6], b2 [n_matpts*4]
        n_params_W1 = 3 * self.hidden_dim
        n_params_b1 = self.hidden_dim
        n_params_W2 = self.hidden_dim * self.n_matpts * 4
        n_params_b2 = self.n_matpts * 4
        total_params = n_params_W1 + n_params_b1 + n_params_W2 + n_params_b2

        # 2L hypernetwork
        hidden = nn.Dense(features=int(total_params / 10), name="hypernetwork", use_bias=True)(micro_params[:, self.micro_vals_used])  # [b, total_params]
        hidden = nn.relu(hidden)
        hyper_out = nn.Dense(features=total_params, name="lu_hidden2", use_bias=True)(hidden)
        # 1L hypernetwork
        # hyper_out = nn.Dense(features=total_params, name="lu_hidden2", use_bias=True)(micro_params[:, self.micro_vals_used])

        # Extract weights and biases for layer 1
        idx = 0
        W1 = hyper_out[:, idx:idx + n_params_W1].reshape(-1, 3, self.hidden_dim)  # [b, 3, hidden_dim]
        idx += n_params_W1
        b1 = hyper_out[:, idx:idx + n_params_b1]  # [b, hidden_dim]
        idx += n_params_b1

        # Extract weights and biases for layer 2
        W2 = hyper_out[:, idx:idx + n_params_W2].reshape(-1, self.hidden_dim, self.n_matpts * 4)  # [b, hidden_dim, n_matpts*4]
        idx += n_params_W2
        b2 = hyper_out[:, idx:idx + n_params_b2]  # [b, n_matpts*6]

        # Define MLP forward pass function
        def mlp_forward(input):
            """2-layer MLP with softplus activation"""
            hidden = jnp.einsum('bi,bij->bj', input, W1) + b1  # [b, hidden_dim]
            # hidden = nn.sigmoid(hidden)
            # hidden = nn.elu(hidden)
            hidden = nn.softplus(hidden)
            return jnp.einsum('bi,bij->bj', hidden, W2) + b2  # [b, n_matpts*4]

        # Bias shift: MLP(x) - MLP(0) to ensure 0 in = 0 out
        mlp_x = mlp_forward(x_flat)
        mlp_0 = mlp_forward(jnp.zeros_like(x_flat))
        params_flat = mlp_x - mlp_0  # [b, n_matpts*4]
        lu_params = params_flat.reshape(-1, self.n_matpts, 4)  # [b, m, 4]

        def construct_C_micro(param_vector):
            """Construct C_micro = L @ U from 4 parameters
            L is lower unit triangular (1s on diagonal), U has elu+1 on diagonal
            """
            l21, u11, u12, u22 = param_vector
            # Lower unit triangular matrix (1s on diagonal)
            L = jnp.array([[1.0, 0.0],
                          [l21, 1.0]])
            # Upper triangular with elu activation for diagonal (elu(x) + 1 ensures positive values)
            U = jnp.array([[nn.elu(u11) + 1.0, u12],
                          [0.0, nn.elu(u22) + 1.0]])
            return L @ U
        C_micro = jax.vmap(jax.vmap(construct_C_micro))(lu_params)  # [b, m, 4] -> C_micro: [b, m, 2, 2]
        return C_micro


class HyperLUv2_3Layer(nn.Module):
    """
    Version 2 with 3 hidden layers:
    - MLP has 3 hidden layers, all width 8, all with softplus activation
    - Hypernetwork is a single linear + bias layer
    - reduced nonlinearity in the LU itself, by using lower unit triangle
    - Increased generality to allow bias & arbitrary activations while ensuring 0 in = 0 out, by using a bias shift (out = MLP(x) - MLP(0))
    """
    n_matpts: int
    hidden_dim: int = 8
    micro_vals_used: list = None

    @nn.compact
    def __call__(self, x, micro_params):
        x_flat = jnp.stack([x[:, 0, 0], x[:, 1, 1], x[:, 0, 1]], axis=1)  # [b, 3]

        # Hypernetwork generates weights and biases for the 3-hidden-layer network
        # Layer 1: W1 [3, hidden_dim], b1 [hidden_dim]
        # Layer 2: W2 [hidden_dim, hidden_dim], b2 [hidden_dim]
        # Layer 3: W3 [hidden_dim, hidden_dim], b3 [hidden_dim]
        # Layer 4 (output): W4 [hidden_dim, n_matpts*4], b4 [n_matpts*4]
        n_params_W1 = 3 * self.hidden_dim
        n_params_b1 = self.hidden_dim
        n_params_W2 = self.hidden_dim * self.hidden_dim
        n_params_b2 = self.hidden_dim
        n_params_W3 = self.hidden_dim * self.hidden_dim
        n_params_b3 = self.hidden_dim
        n_params_W4 = self.hidden_dim * self.n_matpts * 4
        n_params_b4 = self.n_matpts * 4
        total_params = (n_params_W1 + n_params_b1 + n_params_W2 + n_params_b2 +
                        n_params_W3 + n_params_b3 + n_params_W4 + n_params_b4)

        # 2L hypernetwork
        hidden = nn.Dense(features=8, name="lu_hidden1", use_bias=True)(micro_params[:, self.micro_vals_used])  # [b, total_params]
        hidden = nn.sigmoid(hidden)
        hidden = nn.Dense(features=8, name="lu_hidden2", use_bias=True)(hidden)
        hidden = nn.sigmoid(hidden)
        hyper_out = nn.Dense(features=total_params, name="hyper_out", use_bias=True)(hidden)
        # Single linear + bias hypernetwork
        # hyper_out = nn.Dense(features=total_params, name="hypernetwork", use_bias=True)(micro_params[:, self.micro_vals_used])

        # Extract weights and biases for layer 1
        idx = 0
        W1 = hyper_out[:, idx:idx + n_params_W1].reshape(-1, 3, self.hidden_dim)  # [b, 3, hidden_dim]
        idx += n_params_W1
        b1 = hyper_out[:, idx:idx + n_params_b1]  # [b, hidden_dim]
        idx += n_params_b1

        # Extract weights and biases for layer 2
        W2 = hyper_out[:, idx:idx + n_params_W2].reshape(-1, self.hidden_dim, self.hidden_dim)  # [b, hidden_dim, hidden_dim]
        idx += n_params_W2
        b2 = hyper_out[:, idx:idx + n_params_b2]  # [b, hidden_dim]
        idx += n_params_b2

        # Extract weights and biases for layer 3
        W3 = hyper_out[:, idx:idx + n_params_W3].reshape(-1, self.hidden_dim, self.hidden_dim)  # [b, hidden_dim, hidden_dim]
        idx += n_params_W3
        b3 = hyper_out[:, idx:idx + n_params_b3]  # [b, hidden_dim]
        idx += n_params_b3

        # Extract weights and biases for output layer 4
        W4 = hyper_out[:, idx:idx + n_params_W4].reshape(-1, self.hidden_dim, self.n_matpts * 4)  # [b, hidden_dim, n_matpts*4]
        idx += n_params_W4
        b4 = hyper_out[:, idx:idx + n_params_b4]  # [b, n_matpts*4]

        # Define MLP forward pass function
        def mlp_forward(input):
            """3-hidden-layer MLP with softplus activation"""
            h = jnp.einsum('bi,bij->bj', input, W1) + b1  # [b, hidden_dim]
            h = nn.softplus(h)
            h = jnp.einsum('bi,bij->bj', h, W2) + b2  # [b, hidden_dim]
            h = nn.softplus(h)
            h = jnp.einsum('bi,bij->bj', h, W3) + b3  # [b, hidden_dim]
            h = nn.softplus(h)
            return jnp.einsum('bi,bij->bj', h, W4) + b4  # [b, n_matpts*4]

        # Bias shift: MLP(x) - MLP(0) to ensure 0 in = 0 out
        mlp_x = mlp_forward(x_flat)
        mlp_0 = mlp_forward(jnp.zeros_like(x_flat))
        params_flat = mlp_x - mlp_0  # [b, n_matpts*4]
        lu_params = params_flat.reshape(-1, self.n_matpts, 4)  # [b, m, 4]

        def construct_C_micro(param_vector):
            """Construct C_micro = L @ U from 4 parameters
            L is lower unit triangular (1s on diagonal), U has elu+1 on diagonal
            """
            l21, u11, u12, u22 = param_vector
            # Lower unit triangular matrix (1s on diagonal)
            L = jnp.array([[1.0, 0.0],
                          [l21, 1.0]])
            # Upper triangular with elu activation for diagonal (elu(x) + 1 ensures positive values)
            U = jnp.array([[nn.elu(u11) + 1.0, u12],
                          [0.0, nn.elu(u22) + 1.0]])
            return L @ U
        C_micro = jax.vmap(jax.vmap(construct_C_micro))(lu_params)  # [b, m, 4] -> C_micro: [b, m, 2, 2]
        return C_micro


class HyperLLT_1Layer_H1L(nn.Module):
    """
    Version 4: v2, but with same similar L @ L^T as linear layer.
    """
    n_matpts: int
    hidden_dim: int = 8
    micro_vals_used: list = None

    @nn.compact
    def __call__(self, x, micro_params):
        x_flat = jnp.stack([x[:, 0, 0], x[:, 1, 1], x[:, 0, 1]], axis=1)  # [b, 3]

        # Hypernetwork generates weights and biases for the hidden-layer network
        # Layer 1: W1 [3, hidden_dim], b1 [hidden_dim]
        # Layer 2: W2 [hidden_dim, hidden_dim], b2 [hidden_dim]
        n_params_W1 = 3 * self.hidden_dim
        n_params_b1 = self.hidden_dim
        n_params_W2 = self.hidden_dim * self.n_matpts * 3
        n_params_b2 = self.n_matpts * 3
        total_params = (n_params_W1 + n_params_b1 + n_params_W2 + n_params_b2)

        # Single linear + bias hypernetwork
        hyper_out = nn.Dense(features=total_params, name="hypernetwork", use_bias=True)(micro_params[:, self.micro_vals_used])

        # Extract weights and biases for layer 1
        idx = 0
        W1 = hyper_out[:, idx:idx + n_params_W1].reshape(-1, 3, self.hidden_dim)  # [b, 3, hidden_dim]
        idx += n_params_W1
        b1 = hyper_out[:, idx:idx + n_params_b1]  # [b, hidden_dim]
        idx += n_params_b1

        # Extract weights and biases for layer 2
        W2 = hyper_out[:, idx:idx + n_params_W2].reshape(-1, self.hidden_dim, self.n_matpts * 3)  # [b, hidden_dim, hidden_dim]
        idx += n_params_W2
        b2 = hyper_out[:, idx:idx + n_params_b2]  # [b, hidden_dim]

        # Define MLP forward pass function
        def mlp_forward(input):
            """3-hidden-layer MLP with softplus activation"""
            h = jnp.einsum('bi,bij->bj', input, W1) + b1  # [b, hidden_dim]
            h = nn.softplus(h)
            return jnp.einsum('bi,bij->bj', h, W2) + b2  # [b, n_matpts*3]

        # Bias shift: MLP(x) - MLP(0) to ensure 0 in = 0 out
        mlp_x = mlp_forward(x_flat)
        mlp_0 = mlp_forward(jnp.zeros_like(x_flat))
        params_flat = mlp_x - mlp_0  # [b, n_matpts*3]
        lu_params = params_flat.reshape(-1, self.n_matpts, 3)  # [b, m, 3]

        def construct_C_micro(param_vector):
            """
            Construct C_micro = L @ L^T from 3 parameters
            """
            l11, l22, l21 = param_vector
            softplus_offset = jnp.log(2.0)
            L = jnp.array([[nn.softplus(l11) - softplus_offset + 1.0, 0.0],
                          [l21, nn.softplus(l22) - softplus_offset + 1.0]])

            return L @ L.T
        C_micro = jax.vmap(jax.vmap(construct_C_micro))(lu_params)  # [b, m, 3] -> C_micro: [b, m, 2, 2]
        return C_micro


class HyperLLT_1Layer(nn.Module):
    """
    Version 4: v2, but with same similar L @ L^T as linear layer.
    """
    n_matpts: int
    hidden_dim: int = 8
    micro_vals_used: list = None

    @nn.compact
    def __call__(self, x, micro_params):
        x_flat = jnp.stack([x[:, 0, 0], x[:, 1, 1], x[:, 0, 1]], axis=1)  # [b, 3]

        # Hypernetwork generates weights and biases for the hidden-layer network
        # Layer 1: W1 [3, hidden_dim], b1 [hidden_dim]
        # Layer 2: (output): W2 [hidden_dim, n_matpts*3], b2 [n_matpts*3]
        n_params_W1 = 3 * self.hidden_dim
        n_params_b1 = self.hidden_dim
        n_params_W2 = self.hidden_dim * self.n_matpts * 3
        n_params_b2 = self.n_matpts * 3
        total_params = (n_params_W1 + n_params_b1 + n_params_W2 + n_params_b2)

        # hypernetwork
        hidden = nn.Dense(features=8, name="lu_hidden1", use_bias=True)(micro_params[:, self.micro_vals_used])  # [b, total_params]
        hidden = nn.sigmoid(hidden)
        hidden = nn.Dense(features=8, name="lu_hidden2", use_bias=True)(hidden)
        hidden = nn.sigmoid(hidden)
        hyper_out = nn.Dense(features=total_params, name="hyper_out", use_bias=True)(hidden)

        # Extract weights and biases for layer 1
        idx = 0
        W1 = hyper_out[:, idx:idx + n_params_W1].reshape(-1, 3, self.hidden_dim)  # [b, 3, hidden_dim]
        idx += n_params_W1
        b1 = hyper_out[:, idx:idx + n_params_b1]  # [b, hidden_dim]
        idx += n_params_b1

        # Extract weights and biases for layer 2
        W2 = hyper_out[:, idx:idx + n_params_W2].reshape(-1, self.hidden_dim, self.n_matpts * 3)  # [b, hidden_dim, hidden_dim]
        idx += n_params_W2
        b2 = hyper_out[:, idx:idx + n_params_b2]  # [b, hidden_dim]

        # Define MLP forward pass function
        def mlp_forward(input):
            """3-hidden-layer MLP with softplus activation"""
            h = jnp.einsum('bi,bij->bj', input, W1) + b1  # [b, hidden_dim]
            h = nn.softplus(h)
            return jnp.einsum('bi,bij->bj', h, W2) + b2  # [b, n_matpts*3]

        # Bias shift: MLP(x) - MLP(0) to ensure 0 in = 0 out
        mlp_x = mlp_forward(x_flat)
        mlp_0 = mlp_forward(jnp.zeros_like(x_flat))
        params_flat = mlp_x - mlp_0  # [b, n_matpts*3]
        lu_params = params_flat.reshape(-1, self.n_matpts, 3)  # [b, m, 3]

        def construct_C_micro(param_vector):
            """
            Construct C_micro = L @ L^T from 3 parameters
            """
            l11, l22, l21 = param_vector
            softplus_offset = jnp.log(2.0)
            L = jnp.array([[nn.softplus(l11) - softplus_offset + 1.0, 0.0],
                          [l21, nn.softplus(l22) - softplus_offset + 1.0]])

            return L @ L.T
        C_micro = jax.vmap(jax.vmap(construct_C_micro))(lu_params)  # [b, m, 3] -> C_micro: [b, m, 2, 2]
        return C_micro


class HyperLLT_3Layer(nn.Module):
    """
    Version 4: v2, but with same similar L @ L^T as linear layer.
    """
    n_matpts: int
    hidden_dim: int = 8
    micro_vals_used: list = None

    @nn.compact
    def __call__(self, x, micro_params):
        x_flat = jnp.stack([x[:, 0, 0], x[:, 1, 1], x[:, 0, 1]], axis=1)  # [b, 3]

        # Hypernetwork generates weights and biases for the 3-hidden-layer network
        # Layer 1: W1 [3, hidden_dim], b1 [hidden_dim]
        # Layer 2: W2 [hidden_dim, hidden_dim], b2 [hidden_dim]
        # Layer 3: W3 [hidden_dim, hidden_dim], b3 [hidden_dim]
        # Layer 4 (output): W4 [hidden_dim, n_matpts*4], b4 [n_matpts*4]
        n_params_W1 = 3 * self.hidden_dim
        n_params_b1 = self.hidden_dim
        n_params_W2 = self.hidden_dim * self.hidden_dim
        n_params_b2 = self.hidden_dim
        n_params_W3 = self.hidden_dim * self.hidden_dim
        n_params_b3 = self.hidden_dim
        n_params_W4 = self.hidden_dim * self.n_matpts * 3
        n_params_b4 = self.n_matpts * 3
        total_params = (n_params_W1 + n_params_b1 + n_params_W2 + n_params_b2 +
                        n_params_W3 + n_params_b3 + n_params_W4 + n_params_b4)

        # 2L hypernetwork
        hidden = nn.Dense(features=8, name="lu_hidden1", use_bias=True)(micro_params[:, self.micro_vals_used])  # [b, total_params]
        hidden = nn.sigmoid(hidden)
        hidden = nn.Dense(features=8, name="lu_hidden2", use_bias=True)(hidden)
        hidden = nn.sigmoid(hidden)
        hyper_out = nn.Dense(features=total_params, name="hyper_out", use_bias=True)(hidden)
        # Single linear + bias hypernetwork
        # hyper_out = nn.Dense(features=total_params, name="hypernetwork", use_bias=True)(micro_params[:, self.micro_vals_used])

        # Extract weights and biases for layer 1
        idx = 0
        W1 = hyper_out[:, idx:idx + n_params_W1].reshape(-1, 3, self.hidden_dim)  # [b, 3, hidden_dim]
        idx += n_params_W1
        b1 = hyper_out[:, idx:idx + n_params_b1]  # [b, hidden_dim]
        idx += n_params_b1

        # Extract weights and biases for layer 2
        W2 = hyper_out[:, idx:idx + n_params_W2].reshape(-1, self.hidden_dim, self.hidden_dim)  # [b, hidden_dim, hidden_dim]
        idx += n_params_W2
        b2 = hyper_out[:, idx:idx + n_params_b2]  # [b, hidden_dim]
        idx += n_params_b2

        # Extract weights and biases for layer 3
        W3 = hyper_out[:, idx:idx + n_params_W3].reshape(-1, self.hidden_dim, self.hidden_dim)  # [b, hidden_dim, hidden_dim]
        idx += n_params_W3
        b3 = hyper_out[:, idx:idx + n_params_b3]  # [b, hidden_dim]
        idx += n_params_b3

        # Extract weights and biases for output layer 4
        W4 = hyper_out[:, idx:idx + n_params_W4].reshape(-1, self.hidden_dim, self.n_matpts * 3)  # [b, hidden_dim, n_matpts*3]
        idx += n_params_W4
        b4 = hyper_out[:, idx:idx + n_params_b4]  # [b, n_matpts*4]

        # Define MLP forward pass function
        def mlp_forward(input):
            """3-hidden-layer MLP with softplus activation"""
            h = jnp.einsum('bi,bij->bj', input, W1) + b1  # [b, hidden_dim]
            h = nn.softplus(h)
            h = jnp.einsum('bi,bij->bj', h, W2) + b2  # [b, hidden_dim]
            h = nn.softplus(h)
            h = jnp.einsum('bi,bij->bj', h, W3) + b3  # [b, hidden_dim]
            h = nn.softplus(h)
            return jnp.einsum('bi,bij->bj', h, W4) + b4  # [b, n_matpts*3]

        # Bias shift: MLP(x) - MLP(0) to ensure 0 in = 0 out
        mlp_x = mlp_forward(x_flat)
        mlp_0 = mlp_forward(jnp.zeros_like(x_flat))
        params_flat = mlp_x - mlp_0  # [b, n_matpts*4]
        lu_params = params_flat.reshape(-1, self.n_matpts, 3)  # [b, m, 3]

        def construct_C_micro(param_vector):
            """
            Construct C_micro = L @ L^T from 3 parameters
            """
            l11, l22, l21 = param_vector
            softplus_offset = jnp.log(2.0)
            L = jnp.array([[nn.softplus(l11) - softplus_offset + 1.0, 0.0],
                          [l21, nn.softplus(l22) - softplus_offset + 1.0]])

            return L @ L.T
        C_micro = jax.vmap(jax.vmap(construct_C_micro))(lu_params)  # [b, m, 3] -> C_micro: [b, m, 2, 2]
        return C_micro

class LUv3_3Layer(nn.Module):
    """Concatenation-based encoder: micro_params are concatenated with strain
    and processed by a standard MLP with fixed learned parameters (nn.Dense).

    Same LU construction and bias shift as HyperLUv2_3Layer, but replaces the
    hypernetwork with direct concatenation.
    """
    n_matpts: int
    hidden_dim: int = 8
    micro_vals_used: list = None

    @nn.compact
    def __call__(self, x, micro_params):
        x_flat = jnp.stack([x[:, 0, 0], x[:, 1, 1], x[:, 0, 1]], axis=1)  # [b, 3]

        # Concatenate strain with micro parameters
        micro_input = micro_params[:, self.micro_vals_used]  # [b, k]
        mlp_input = jnp.concatenate([x_flat, micro_input], axis=1)  # [b, 3+k]

        # Build zero-strain input for bias shift (zeros for x_flat, keep micro)
        mlp_input_zero = jnp.concatenate([jnp.zeros_like(x_flat), micro_input], axis=1)  # [b, 3+k]

        dense1 = nn.Dense(features=self.hidden_dim, name="lu_dense1")
        dense2 = nn.Dense(features=self.hidden_dim, name="lu_dense2")
        dense3 = nn.Dense(features=self.hidden_dim, name="lu_dense3")
        dense_out = nn.Dense(features=self.n_matpts * 4, name="lu_dense_out")

        def mlp(inp):
            """3-hidden-layer MLP with softplus activation."""
            h = nn.softplus(dense1(inp))
            h = nn.softplus(dense2(h))
            h = nn.softplus(dense3(h))
            return dense_out(h)

        # Bias shift: MLP(x||micro) - MLP(0||micro) ensures zero strain → zero output
        params_flat = mlp(mlp_input) - mlp(mlp_input_zero)  # [b, n_matpts*4]
        lu_params = params_flat.reshape(-1, self.n_matpts, 4)  # [b, m, 4]

        def construct_C_micro(param_vector):
            """Construct C_micro = L @ U from 4 parameters."""
            l21, u11, u12, u22 = param_vector
            L = jnp.array([[1.0, 0.0],
                          [l21, 1.0]])
            U = jnp.array([[nn.elu(u11) + 1.0, u12],
                          [0.0, nn.elu(u22) + 1.0]])
            return L @ U
        C_micro = jax.vmap(jax.vmap(construct_C_micro))(lu_params)  # [b, m, 2, 2]
        return C_micro


#         dense_out = nn.Dense(features=self.n_matpts * 6, name="lu_dense_out")
#
#         def mlp(inp):
#             """3-hidden-layer MLP with softplus activation."""
#             h = nn.softplus(dense1(inp))
#             h = nn.softplus(dense2(h))
#             h = nn.softplus(dense3(h))
#             return dense_out(h)
#
#         # Bias shift: MLP(x||micro) - MLP(0||micro) ensures zero strain → zero output
#         params_flat = mlp(mlp_input) - mlp(mlp_input_zero)  # [b, n_matpts*4]
#         lu_params = params_flat.reshape(-1, self.n_matpts, 6)  # [b, m, 4]
#
#         def construct_C_micro(param_vector):
#             """Construct C_micro = L @ U from 4 parameters."""
#             l11, l21, l22, u11, u12, u22 = param_vector
#             L = jnp.array([[nn.elu(l11) + 1.0, 0.0],
#                           [l21, nn.elu(l22) + 1.0]])
#             U = jnp.array([[nn.elu(u11) + 1.0, u12],
#                           [0.0, nn.elu(u22) + 1.0]])

class PointLayer(nn.Module):
    """Custom decoder sparse layer with constrained connectivity pattern and weights.

    Each material point's outputs are connected to the PRNN outputs with a single weight.
    All weights are positive and sum to one.
    We assume voigt notation
    """
    n_matpts: int   # m: Number of material points

    @nn.compact
    def __call__(self, x, micro_params):
        # x shape: [b, m, o]

        # Create unconstrained weights parameter
        raw_weights = self.param('raw_weights',
                                 nn.initializers.uniform(dtype=jnp.float32),    # NOTE: uniform distribution
                                 # nn.initializers.glorot_normal(dtype=jnp.float32),    # not supported for 1D
                                 (self.n_matpts,))  # [m]

        # Apply softplus to ensure weights are positive
        weights = nn.softplus(raw_weights)  # [m]
        # Scale weights to sum to one
        weights = weights / jnp.sum(weights)  # [m]

        # Compute point wise
        output = jnp.einsum('bmo,m->bo', x, weights)  # [b, n, o]

        return output


class HyperPointLayer(nn.Module):
    """
    Hypernetwork for the PointLayer
    the weights of the PointLayer are generated by a small neural network based on micro_params.
    """
    hidden_features: int = 5
    mat_pts: int = 10   # m: number of outputs of the hypernet
    micro_vals_used: list = None

    @nn.compact
    def __call__(self, x, micro_params):
        # x shape: [b, m, o]
        # micro_params shape: [b, k] with k the number of micro parameters. Only subset micro_vals_used is used.

        # 2L
        # hyp_l1 = nn.relu(nn.Dense(features=self.hidden_features, name="point_hypernet_0", use_bias=True)(micro_params))
        # param_vector = nn.Dense(features=self.mat_pts, name="point_hypernet_1", use_bias=True)(hyp_l1)

        # 1L
        param_vector = nn.Dense(features=self.mat_pts, name="point_hypernet", use_bias=True)(micro_params[:, self.micro_vals_used])

        # Point layer operation
        # Apply softplus to ensure weights are positive
        weights = nn.softplus(param_vector)  # [b,m]
        # Scale weights to sum to one
        weights = weights / jnp.sum(weights, axis=1, keepdims=True)  # [b,m]

        output = jnp.einsum('bmo,bm->bo', x, weights)

        return output


class HyperPointFreeLayer(nn.Module):
    """
    Hypernetwork for the PointLayer
    the weights of the PointLayer are generated by a small neural network based on micro_params.
    """
    hidden_features: int = 5
    mat_pts: int = 10   # m: number of outputs of the hypernet
    micro_vals_used: list = None

    @nn.compact
    def __call__(self, x, micro_params):
        param_vector = nn.Dense(features=self.mat_pts, name="point_hypernet", use_bias=True)(micro_params[:, self.micro_vals_used])
        # Apply softplus to ensure weights are positive
        weights = nn.softplus(param_vector)  # [b,m]
        # Weights don't sum to one

        return jnp.einsum('bmo,bm->bo', x, weights)


class SparseLayer(nn.Module):
    """Custom decoder sparse layer with constrained connectivity pattern and weights.

    Each material point's output is connected with a weight to the corresponding PRNN output comonent.
    All weights are positive, and optionally per component sum to one.
    """
    n_matpts: int   # m: Number of material points
    n_outputs: int  # o: Number of output components
    scale_weights_one: bool  # option to scale weights to one component wise

    @nn.compact
    def __call__(self, x, micro_params):
        # x shape: [b, m, o]

        # Create weights parameter
        raw_weights = self.param('raw_weights',
                                 # nn.initializers.he_uniform(dtype=jnp.float32),
                                 nn.initializers.glorot_normal(dtype=jnp.float32),
                                 (self.n_matpts,self.n_outputs))

        # Apply softplus to ensure weights are positive
        weights = nn.softplus(raw_weights)  # [m, o]

        if self.scale_weights_one:
            # Scale weights to sum to one component wise
            weights = weights / jnp.sum(weights, axis=0)  # [m, o]

        # Compute layer using Einstein summation convention
        return jnp.einsum('bmo,mo->bo', x, weights)


class HyperSparseLayer(nn.Module):
    """
    Hypernetwork for the SparseLayer
    the weights of the SparseLayer are generated by a small neural network based on micro_params.
    """
    mat_pts: int = 10   # m: number of material points
    n_outputs: int = 3  # o: number of output components
    scale_weights_one: bool = False  # option to scale weights to one component wise
    micro_vals_used: list = None

    @nn.compact
    def __call__(self, x, micro_params):
        # x shape: [b, m, o]
        # micro_params shape: [b, k] with k the number of micro parameters. Only subset micro_vals_used is used.

        # hyp_hidden = nn.Dense(features=self.mat_pts * 3, name="hyperSparse_1", use_bias=True)(micro_params[:, self.micro_vals_used])
        # hyp_hidden = nn.relu(hyp_hidden)
        # param_vector = nn.Dense(features=self.mat_pts * 3, name="hyperSparse_2", use_bias=True)(hyp_hidden)

        # Hypernetwork (either linear layer, or small MLP)
        param_vector = nn.Dense(features=self.mat_pts * self.n_outputs, name="sparse_hypernet", use_bias=True)(micro_params[:, self.micro_vals_used])

        # Reshape to [b, m, o]
        param_vector = param_vector.reshape(-1, self.mat_pts, self.n_outputs)

        # Sparse layer operation
        weights = nn.softplus(param_vector)  # [b, m, o]

        if self.scale_weights_one:
            # Scale weights to sum to one component wise
            weights = weights / jnp.sum(weights, axis=1, keepdims=True)  # [b, m, o]
        return jnp.einsum('bmo,bmo->bo', x, weights)


class HyperSparse3Layer(nn.Module):
    """
    Hypernetwork for the SparseLayer
    the weights of the SparseLayer are generated by a small neural network based on micro_params.
    """
    mat_pts: int = 10   # m: number of material points
    n_outputs: int = 3  # o: number of output components
    scale_weights_one: bool = False  # option to scale weights to one component wise
    micro_vals_used: list = None

    @nn.compact
    def __call__(self, x, micro_params):
        # x shape: [b, m, o]
        # micro_params shape: [b, k] with k the number of micro parameters. Only subset micro_vals_used is used.

        hyp_hidden = nn.Dense(features=self.mat_pts, name="hyperSparse_1", use_bias=True)(micro_params[:, self.micro_vals_used])
        hyp_hidden = nn.sigmoid(hyp_hidden)
        hyp_hidden = nn.Dense(features=self.mat_pts * 2, name="hyperSparse_2", use_bias=True)(hyp_hidden)
        hyp_hidden = nn.sigmoid(hyp_hidden)
        param_vector = nn.Dense(features=self.mat_pts * self.n_outputs, name="hyperSparse_3", use_bias=True)(hyp_hidden)  # [b, 3*m]

        param_vector = param_vector.reshape(-1, self.mat_pts, self.n_outputs)
        weights = nn.softplus(param_vector)  # [b, m, o]
        if self.scale_weights_one:
            weights = weights / jnp.sum(weights, axis=1, keepdims=True)  # [b, m, o]
        return jnp.einsum('bmo,bmo->bo', x, weights)


class ResidualHyperSparseLayer(nn.Module):
    """Residual hypernetwork for SparseLayer.

    Adds a learned linear correction to frozen base weights:
    raw_weights = base + W @ (micro_params - micro_params_base), no bias.
    Zero deviation at the base point by construction.

    Extract base params from a trained standard PRNN:
        base_raw_weights = trained_params['params']['decoder']['raw_weights']
    """
    n_matpts: int
    n_outputs: int
    base_raw_weights: object     # [m, o] frozen from pre-trained SparseLayer
    micro_params_base: object    # [k] micro_params of the base configuration
    max_delta: float = 1.0       # maximum absolute correction per weight
    scale_weights_one: bool = False
    micro_vals_used: list = None

    @nn.compact
    def __call__(self, x, micro_params):
        # x shape: [b, m, o]
        centered_micro_params = micro_params[:, self.micro_vals_used] - self.micro_params_base[jnp.array(self.micro_vals_used)]

        delta = nn.Dense(features=self.n_matpts * self.n_outputs, use_bias=False, name="residual_decoder", kernel_init=nn.initializers.normal(stddev=1e-3))(centered_micro_params)  # [b, m*o]
        delta = delta.reshape(-1, self.n_matpts, self.n_outputs)  # [b, m, o]
        # delta = self.max_delta * jnp.tanh(delta)

        raw_weights = self.base_raw_weights[None, :, :] + delta  # [b, m, o]
        weights = nn.softplus(raw_weights)  # [b, m, o]

        if self.scale_weights_one:
            weights = weights / jnp.sum(weights, axis=1, keepdims=True)

        return jnp.einsum('bmo,bmo->bo', x, weights)


class SoftLayer(nn.Module):
    """Custom decoder layer that applies softplus to weights before the linear transform."""
    n_matpts: int   # m: Number of material points
    n_outputs: int  # o: Number of output components
    use_bias: bool = False

    @nn.compact
    def __call__(self, x, micro_params):
        # x shape: [b, m, o]  (=b,m,4)        p = m * o

        # Create unconstrained weights parameter
        raw_weights = self.param('raw_weights',
                                 # nn.initializers.he_uniform(dtype=jnp.float32),
                                 nn.initializers.glorot_normal(dtype=jnp.float32),
                                 (self.n_matpts * self.n_outputs,self.n_outputs))   # [p, o]

        # Apply softplus to ensure weights are positive
        weights = nn.softplus(raw_weights)  # [p, o]

        # reshape x to be [b, m * o]
        x = x.reshape(-1, self.n_matpts * self.n_outputs)  # [b, m * o]

        # linear transform, essentially dot product between weights and input
        # Compute using Einstein summation convention
        output = jnp.einsum('bp,po->bo', x, weights)  # [b, o]

        if self.use_bias:
            bias = self.param('bias',
                              nn.initializers.zeros,
                              (self.n_outputs,))
            output = output + bias

        return output


class HyperSoftLayer(nn.Module):
    """Hypernetwork version of SoftLayer.

    The weights are generated by a small neural network based on micro_params,
    allowing the soft decoder to be conditioned on material properties.
    """
    n_matpts: int   # m: Number of material points
    n_outputs: int  # o: Number of output components
    use_bias: bool = False
    micro_vals_used: list = None

    @nn.compact
    def __call__(self, x, micro_params):
        # x shape: [b, m, o]  (=b,m,3)        p = m * o

        # Generate weights from micro_params using a hypernetwork
        # Output shape should be [b, p, o] where p = m * o
        p = self.n_matpts * self.n_outputs
        params = nn.Dense(features=p * self.n_outputs, name="soft_hypernet", use_bias=True)(micro_params[:, self.micro_vals_used])

        # Reshape to [b, p, o]
        weights = params.reshape(-1, p, self.n_outputs)  # [b, p, o]

        # Apply softplus to ensure weights are positive
        pos_weights = nn.softplus(weights)  # [b, p, o]

        # reshape x to be [b, m * o]
        x_flat = x.reshape(-1, p)  # [b, p]

        # linear transform, essentially dot product between weights and input
        # Compute using Einstein summation convention
        output = jnp.einsum('bp,bpo->bo', x_flat, pos_weights)  # [b, o]

        if self.use_bias:
            bias = self.param('bias',
                              nn.initializers.zeros,
                              (self.n_outputs,))
            output = output + bias

        return output


class PRNN(nn.Module):
    """Physically Recurrent Neural Network using JAX for single or multiple materials."""
    n_outputs: int      # o: Number of output components
    n_matpts: int | tuple     # m: Number of material points (int for single, tuple for multiple materials)
    decoder_type: str   # Type of decoder layer to use
    encoder_type: str  # Type of encoder layer to use
    stress_normalizer: object
    encoder_micro_features: list
    decoder_micro_features: list
    material_micro_features: list = None  # List of micro features relevant to the material model
    use_multiple_materials: bool = False  # Flag to determine single vs multiple material handling
    base_encoder_params: object = None   # Frozen base encoder weights for residual hypernetwork
    base_decoder_params: object = None   # Frozen base decoder weights for residual hypernetwork
    micro_params_base: object = None     # Base micro_params for centering in residual hypernetwork
    w_max: float = 1.25
    stress_scaling_index: int = None     # Index into micro_params for per-sample stress scaling (e.g. mu)

    def setup(self):
        # Calculate total material points
        if self.use_multiple_materials:
            total_matpts = int(sum(self.n_matpts))  # Sum for multiple materials
        else:
            total_matpts = self.n_matpts  # Single material

        # Encoder layer
        if self.encoder_type == 'DeformationGradientLayer':
            self.encoder = DeformationGradientLayer(n_matpts=total_matpts, w_max=self.w_max)
        elif self.encoder_type == 'HyperDeformationGradientLayer_grad':
            self.encoder = HyperDeformationGradientLayer_grad(n_matpts=total_matpts, micro_vals_used=self.encoder_micro_features, w_max=self.w_max)
        elif self.encoder_type == 'HyperDeformationGradientLayer':
            self.encoder = HyperDeformationGradientLayer(n_matpts=total_matpts, micro_vals_used=self.encoder_micro_features, w_max=self.w_max)
        elif self.encoder_type == 'HyperDeformationGradientLayer_1L':
            self.encoder = HyperDeformationGradientLayer_1L(n_matpts=total_matpts, micro_vals_used=self.encoder_micro_features, w_max=self.w_max)
        elif self.encoder_type == 'LULayer':
            self.encoder = LULayer(n_matpts=total_matpts)
        elif self.encoder_type == 'HyperLULayer':
            self.encoder = HyperLULayer(n_matpts=total_matpts, micro_vals_used=self.encoder_micro_features)
        elif self.encoder_type == 'HyperLUSoftLayer':
            self.encoder = HyperLUSoftLayer(n_matpts=total_matpts, micro_vals_used=self.encoder_micro_features)
        elif self.encoder_type == 'HyperLUSoftSimplerLayer':
            self.encoder = HyperLUSoftSimplerLayer(n_matpts=total_matpts, micro_vals_used=self.encoder_micro_features)
        elif self.encoder_type == 'HyperLUv2Layer':
            self.encoder = HyperLUv2Layer(n_matpts=total_matpts, hidden_dim=8, micro_vals_used=self.encoder_micro_features)
        elif self.encoder_type == 'HyperLUv2_3Layer':
            self.encoder = HyperLUv2_3Layer(n_matpts=total_matpts, hidden_dim=8, micro_vals_used=self.encoder_micro_features)
        elif self.encoder_type == 'HyperLLT_3Layer':
            self.encoder = HyperLLT_3Layer(n_matpts=total_matpts, hidden_dim=8, micro_vals_used=self.encoder_micro_features)
        elif self.encoder_type == 'HyperLLT_1Layer':
            self.encoder = HyperLLT_1Layer(n_matpts=total_matpts, hidden_dim=8, micro_vals_used=self.encoder_micro_features)
        elif self.encoder_type == 'HyperLLT_1Layer_H1L':
            self.encoder = HyperLLT_1Layer_H1L(n_matpts=total_matpts, hidden_dim=8, micro_vals_used=self.encoder_micro_features)
        elif self.encoder_type == 'LUv3_3Layer':
            self.encoder = LUv3_3Layer(n_matpts=total_matpts, hidden_dim=8, micro_vals_used=self.encoder_micro_features)
        elif self.encoder_type == 'ResidualHyperEncoderLayer':
            self.encoder = ResidualHyperEncoderLayer(n_matpts=total_matpts, base_cholesky_params=self.base_encoder_params, micro_params_base=self.micro_params_base, micro_vals_used=self.encoder_micro_features, w_max=self.w_max)
        elif self.encoder_type == 'LUv2Layer':
            self.encoder = LUv2Layer(n_matpts=total_matpts, hidden_dim=8)
        elif self.encoder_type == 'ResidualHyperLUv2EncoderLayer':
            self.encoder = ResidualHyperLUv2EncoderLayer(n_matpts=total_matpts, base_mlp_params=self.base_encoder_params, micro_params_base=self.micro_params_base, micro_vals_used=self.encoder_micro_features)
        else:
            raise ValueError(f"Unknown encoder type: {self.encoder_type}")

        # Decoder / homogenization layer
        if self.decoder_type == 'PointLayer':
            self.decoder = PointLayer(n_matpts=total_matpts)
        elif self.decoder_type == 'SoftLayer':
            self.decoder = SoftLayer(n_matpts=total_matpts, n_outputs=self.n_outputs, use_bias=False)
        elif self.decoder_type == 'HyperSoftLayer':
            self.decoder = HyperSoftLayer(n_matpts=total_matpts, n_outputs=self.n_outputs, use_bias=False, micro_vals_used=self.decoder_micro_features)
        elif self.decoder_type == 'SparseLayer':
            self.decoder = SparseLayer(n_matpts=total_matpts, n_outputs=self.n_outputs, scale_weights_one=False)
        elif self.decoder_type == 'HyperPointLayer':
            self.decoder = HyperPointLayer(mat_pts=total_matpts, micro_vals_used=self.decoder_micro_features)
        elif self.decoder_type == 'HyperSparseLayer':
            self.decoder = HyperSparseLayer(mat_pts=total_matpts, n_outputs=self.n_outputs, scale_weights_one=False, micro_vals_used=self.decoder_micro_features)
        elif self.decoder_type == 'HyperSparseScalingLayer':
            self.decoder = HyperSparseLayer(mat_pts=total_matpts, n_outputs=self.n_outputs, scale_weights_one=True, micro_vals_used=self.decoder_micro_features)
        elif self.decoder_type == 'HyperSparse3Layer':
            self.decoder = HyperSparse3Layer(mat_pts=total_matpts, n_outputs=self.n_outputs, scale_weights_one=False, micro_vals_used=self.decoder_micro_features)
        elif self.decoder_type == 'ResidualHyperSparseLayer':
            self.decoder = ResidualHyperSparseLayer(n_matpts=total_matpts, n_outputs=self.n_outputs, base_raw_weights=self.base_decoder_params, micro_params_base=self.micro_params_base, scale_weights_one=False, micro_vals_used=self.decoder_micro_features)
        else:
            raise ValueError(f"Unknown decoder type: {self.decoder_type}")


    def __call__(self, x, material, micro_params=None, reshape=True):
        # Input x: Green-Lagrange strain E. Symmetric by definition.
        # if the shape of x is not length 3, transform it to be [batch_size, 2, 2]. We can combine timesteps & different runs, since there is no time dependency in the model.
        # the name "b" is perhaps a bit misleading, since it is batches * number of timesteps
        # "m" = number of material points
        s = int(x.shape[1])

        if reshape:  #
            original_shape = x.shape
            x = x.reshape(-1, 2, 2)  # Reshape to [batch_size, 2, 2] if not already in that shape

        b = int(x.shape[0])     # b: note that this == batch_size * timesteps, as we don't need to distinguish between them (no time dependent material behavior)

        # Expand micro_params from [batch_size] -> [batch_size * timesteps] to match sequence size
        if micro_params is not None:
            micro_params = jnp.broadcast_to(micro_params[:, None, :], (micro_params.shape[0], s, micro_params.shape[1]))
            micro_params = micro_params.reshape(b, micro_params.shape[-1])  # reshape to [b, k] with k the number of micro parameters

        # --- Apply Encoder on all inputs ---
        C_micro = self.encoder(x, micro_params)   # [b, m, 2, 2]

        if self.use_multiple_materials:
            # Handle multiple materials case
            # Split the C_micros into separate arrays, one for each material
            C_neohooke, C_rest = jnp.split(C_micro, self.n_matpts[:1], axis=1)  # List of [b, m_i, 2, 2] for each material i

            # shape back to b*m
            C_neohooke = C_neohooke.reshape(-1, 2, 2)
            C_rest = C_rest.reshape(-1, 2, 2)

            # --- Apply Neo-Hookean material model ---
            ## TODO: This assumes that mu is 1st, lambda_ is second in "mat_micro_features"
            mu_per_sample = micro_params[:, self.material_micro_features[0]]
            mus = jnp.repeat(mu_per_sample, self.n_matpts[0], axis=0)  # [b * m_i]

            lambda_per_sample = micro_params[:, self.material_micro_features[1]]
            lambdas = jnp.repeat(lambda_per_sample, self.n_matpts[0], axis=0)  # [b * m_i]
            micro_stresses_neo = neohooke.jit_vmap_neo_hooke_pk2_variable(C_neohooke, mus, lambdas)  # PK2 output, symmetric [b * m_i, 2, 2]
            # --- Apply Neo-Hookean material model for wood ---
            wood_mu = 4.727e3
            wood_lambda = 14.182e3
            n_wood_pts = C_rest.shape[0]  # Total number of wood material points (b * m_j)
            wood_mus = jnp.full((n_wood_pts,), wood_mu)
            wood_lambdas = jnp.full((n_wood_pts,), wood_lambda)
            micro_stresses_rest = neohooke.jit_vmap_neo_hooke_pk2_variable(C_rest, wood_mus, wood_lambdas)  # [b * m_j, 2, 2]

            # reshape individually back to [b, m, ..]
            micro_stresses_neo = micro_stresses_neo.reshape(b, self.n_matpts[0], 2, 2)  # [b, m_i, 2, 2]
            micro_stresses_rest = micro_stresses_rest.reshape(b, self.n_matpts[1], 2, 2)  # [b, m_j, 2, 2]

            # Combine the stresses from both materials
            micro_stresses = jnp.concatenate((micro_stresses_neo, micro_stresses_rest), axis=1)  # [b, (m_i + m_j), 2, 2]
        else:
            # Handle single material case
            C_micro = C_micro.reshape(-1, 2, 2)

            # --- Apply Neo-Hookean material model on all inputs ---
            # micro_stresses = neohooke.jit_vmap_neo_hooke_train_update(C_micro, material)  # [b * m, 2, 2]
            mu_per_sample = micro_params[:, self.material_micro_features[0]]
            mus = jnp.repeat(mu_per_sample, self.n_matpts, axis=0)  # [b * m_i]

            lambda_per_sample = micro_params[:, self.material_micro_features[1]]
            lambdas = jnp.repeat(lambda_per_sample, self.n_matpts, axis=0)  # [b * m_i]
            # micro_stresses = neohooke.jit_vmap_neo_hooke_variable_mu(C_micro, mus, lambdas)
            micro_stresses = neohooke.jit_vmap_neo_hooke_pk2_variable(C_micro, mus, lambdas)    # [b * m, 2, 2]
            micro_stresses = micro_stresses.reshape(b, self.n_matpts, 2, 2) # expand extra dim: [b, m, 2, 2]

        # Go back to tensor notation:
        micro_stresses_tensor = matrix_to_tensor(micro_stresses, symmetric=True)    # PK2 is symmetric [b, m, 3]

        # normalize (with optional per-sample stress scaling, e.g. dividing by mu)
        scale = micro_params[:, self.stress_scaling_index] if self.stress_scaling_index is not None else None
        micro_stresses_norm = self.stress_normalizer.normalize(micro_stresses_tensor, scale=scale)

        # --- Apply Decoder on all inputs ---
        outputs = self.decoder(micro_stresses_norm, micro_params)  # [b, o]

        # reshape back to original shape
        if reshape:
            if len(original_shape) == 4:
                outputs = outputs.reshape((original_shape[0], original_shape[1], self.n_outputs))

        return outputs


def create_prnn_model(n_features=4, n_outputs=3, n_matpts=8, random_key=jax.random.PRNGKey(0), encoder_type='DeformationGradientLayer', decoder_type='PointLayer', stress_normalizer=None, num_mat_features=0, enc_m_feats=[], dec_m_feats=[], mat_m_feats=[], base_encoder_params=None, base_decoder_params=None, micro_params_base=None, w_max=1.25, stress_scaling_index=None):
    """Create and initialize a PRNN model with material parameters."""
    # Determine if we're using multiple materials
    use_multiple_materials = isinstance(n_matpts, list)

    # Create model
    model = PRNN(
        n_outputs=n_outputs,
        n_matpts=n_matpts,
        decoder_type=decoder_type,
        encoder_type=encoder_type,
        stress_normalizer=stress_normalizer,
        encoder_micro_features=enc_m_feats,
        decoder_micro_features=dec_m_feats,
        material_micro_features=mat_m_feats,
        use_multiple_materials=use_multiple_materials,
        base_encoder_params=base_encoder_params,
        base_decoder_params=base_decoder_params,
        micro_params_base=micro_params_base,
        w_max=w_max,
        stress_scaling_index=stress_scaling_index,
    )

    # Create appropriate material configuration
    # Note: deprecated! Material parameters are now passed as micro variables instead. 2nd material model is fixed in the code.
    # This section, and the passing of material around, is kept in case two different material models are required in the future.
    if use_multiple_materials:
        # material_neo = neohooke.create_material()
        # material_neo = neohooke.create_material(lambda_=21.346, mu_=14.231)
        material_neo = neohooke.create_material(lambda_=150., mu_=100.)
        # material_bonet = bonet.create_material(Ea = 1.2e3, E = 1.2e3, Ga = 0.4e3, nua = 0.3, nu=0.3, fibdir=(1.0, 0.0, 0.0))
        # material_bonet = bonet.create_material(Ea = 13.e3, E = 13.e3, Ga = 0.965e3, nua = 0.375, nu=0.03, fibdir=(1.0, 0.0, 0.0))
        material = {
            'neohooke': material_neo,
            # 'orthotropic': material_orthotropic,
            # 'bonet': material_bonet
        }
    else:
        # Single material case
        material = neohooke.create_material(lambda_=150., mu_=100.)

    print(f'New PRNN: Encoder {encoder_type} - Decoder {decoder_type} - Material layer size (points) {model.n_matpts} - Multiple materials: {use_multiple_materials}')

    if num_mat_features == 0:
        micro_params = None
    else:
        micro_params = jnp.zeros((1, num_mat_features))  # Dummy micro parameters input

    # Initialize model parameters
    params = model.init(random_key,
                       jnp.zeros((1, 1, 2, 2)),  # Dummy input
                       material,   # Material propertes
                       micro_params  # micro parameters
                       )

    return model, params, material
